{% set name = "graypy" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2201d55bac16f82cfec445214be45506c5f86a596de802cc9374347eab9d4bf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - graypy

about:
  home: https://github.com/severb/graypy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python logging handler that sends messages in GELF (Graylog Extended Log Format).
  doc_url: https://pypi.org/project/graypy/
  dev_url: https://github.com/severb/graypy

extra:
  recipe-maintainers:
    - anthchirp
