travis:
  secure:
    BINSTAR_TOKEN: M4ndjd2AJLExf7oUCqbh++WIXj2VLRC1gMM4c/fMYjtVgSOU+YTmZYrXHaa1RSplYs6vQJ/PssLXs004G7jF7SqhKBdteg+iJplVybJ4GoE/fPylOCnMIHmtRCB2TIjlHZhyf+Zk4QxMUe9UdwACn0tKEKAGimtgadBVb3YjKNIgA81sRh4sJUgdPYmeTsN5dbNOZvZPtZDzCSygPZFI6jWWByfihTj54QIi2G6QXKkn39uN8P8d/1YWAkkAvNRu5OiKdHC0cKPSA361JmoWM6lqPtmPN5PGy+1z8e9V52RH9WAy4Nu9oskZQ8uB/uXiqgjzGUtEPD+h0s0YFgyiiKM4Wq+EJe1QqOjKM9S8Me0HhuAUIV6LbLCKNWXy4bLY0GPmJJCBvo+iPIjTDF6Gf/9VUoWevYo9TpRtI5rdP+/XggNj5UOKxrKISomYCBy32Jj99OduOvX3DVSV9MwOl76PQiTZ82qKNXQIKJ5On6SlgqfMRhkFXT5B4dq8NBX5TXwluOfyi/1OTW2DdhtFqyzkkq3CynZ9xSMgXI4wKwykOig8cwYgaLqnaR1u6cCyLbl7+yBQYEZu0lalukL5zwCAnOTWG7rhsapILKFd/hzWxp1qpbRgZIo4rVJDJLKl1lvaARfHfuLJN9AF0oRxOG2wlvMrPci+tRFO0OZjcfE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
